broker.id=0
listeners=PLAINTEXT://kafka:9092
log.dirs=/var/lib/kafka/logs
zookeeper.connect=zookeeper:2181
auto.create.topics.enable=true
num.partitions=1
message.max.bytes=1000000
replication.factor=1
min.insync.replicas=1
acks=all